"""relate users to books

Revision ID: 1073aca9c75c
Revises: f48b481df82f
Create Date: 2025-11-07 14:04:20.515626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1073aca9c75c'
down_revision: Union[str, Sequence[str], None] = 'f48b481df82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user')
    # ### end Alembic commands ###
